version: 0.2

phases:
  install:
    commands:
      - sudo apt update
      - sudo apt install software-properties-common -y
      - sudo add-apt-repository ppa:deadsnakes/ppa
      - sudo apt install -y python3.9
  pre_build:
    commands:
      - python3 --version
      - pip3 --version
      - pip3 install Flask
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
